#ifndef _TIPO_JUEGO_H
    #define _TIPO_JUEGO_H

    char __tablero_inicial[FILAS][COLUMNAS][3] = {\
            {TORRE_BLANCO, CABALLO_BLANCO, ALFIL_BLANCO, REINA_BLANCO, REY_BLANCO, ALFIL_BLANCO, CABALLO_BLANCO, TORRE_BLANCO},\
            {PEON_BLANCO, PEON_BLANCO, PEON_BLANCO, PEON_BLANCO, PEON_BLANCO, PEON_BLANCO, PEON_BLANCO, PEON_BLANCO},\
            {NADA, NADA, NADA, NADA, NADA, NADA, NADA, NADA},\
            {NADA, NADA, NADA, NADA, NADA, NADA, NADA, NADA},\
            {NADA, NADA, NADA, NADA, NADA, NADA, NADA, NADA},\
            {NADA, NADA, NADA, NADA, NADA, NADA, NADA, NADA},\
            {PEON_NEGRO, PEON_NEGRO, PEON_NEGRO, PEON_NEGRO, PEON_NEGRO, PEON_NEGRO, PEON_NEGRO, PEON_NEGRO},\
            {TORRE_NEGRO, CABALLO_NEGRO, ALFIL_NEGRO, REINA_NEGRO, REY_NEGRO , ALFIL_NEGRO, CABALLO_NEGRO, TORRE_NEGRO}\
    };

    #if defined(TABLERO_PERSONALIZADO)
        #define INICIALIZAR_JUEGO(args) Inicializar(tableroPersonalizado, args)

    #else
        #define INICIALIZAR_JUEGO(args) Inicializar(__tablero_inicial, args)

    #endif
#endif